apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: php
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-conn
spec:
  ports:
  - port: 3307
  selector:
    app: mysql
  clusterIP: None